# File to test functions related to data loader

#### 1. Import libraries

In [1]:
import sys
from pathlib import Path

project_root = Path("..").resolve()
sys.path.append(str(project_root))

import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path

In [14]:
from src.data_loader import load_raw_data

In [3]:
df_RowData = load_raw_data("../data/supply_delivery_history.csv")
df_RowData.head()

,ID,Country,Fulfill Via,Shipment Mode,Scheduled Delivery Date,Delivered to Client Date,Delivery Recorded Date,Product Group,Sub Classification,Vendor,...,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,Côte d'Ivoire,Direct Drop,Air,2-Jun-06,2-Jun-06,2-Jun-06,HRDT,HIV test,RANBAXY Fine Chemicals LTD.,...,30,19,551,29,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,NaN
1,3,Vietnam,Direct Drop,Air,14-Nov-06,14-Nov-06,14-Nov-06,ARV,Pediatric,Aurobindo Pharma Limited,...,240,1000,6200,6.2,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,NaN
2,4,Côte d'Ivoire,Direct Drop,Air,27-Aug-06,27-Aug-06,27-Aug-06,HRDT,HIV test,Abbott GmbH & Co. KG,...,100,500,40000,80,0.8,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,NaN
3,15,Vietnam,Direct Drop,Air,1-Sep-06,1-Sep-06,1-Sep-06,ARV,Adult,SUN PHARMACEUTICAL INDUSTRIES LTD (RANBAXY LAB...,...,60,31920,127360.8,3.99,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,NaN
4,16,Vietnam,Direct Drop,Air,11-Aug-06,11-Aug-06,11-Aug-06,ARV,Adult,Aurobindo Pharma Limited,...,60,38000,121600,3.2,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,NaN

In [4]:
from src.data_loader import load_clean_data

In [5]:
df_CleanData = load_clean_data("../data/supply_delivery_history_clean.csv")
df_CleanData.head()

,ID,Country,Fulfill Via,Shipment Mode,Scheduled Delivery Date,Delivered to Client Date,Delivery Recorded Date,Product Group,Sub Classification,Vendor,...,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,Côte d'Ivoire,Direct Drop,Air,2-Jun-06,2-Jun-06,2-Jun-06,HRDT,HIV test,RANBAXY Fine Chemicals LTD.,...,30,19,551,29,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,NaN
1,3,Vietnam,Direct Drop,Air,14-Nov-06,14-Nov-06,14-Nov-06,ARV,Pediatric,Aurobindo Pharma Limited,...,240,1000,6200,6.2,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,NaN
2,4,Côte d'Ivoire,Direct Drop,Air,27-Aug-06,27-Aug-06,27-Aug-06,HRDT,HIV test,Abbott GmbH & Co. KG,...,100,500,40000,80,0.8,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,NaN
3,15,Vietnam,Direct Drop,Air,1-Sep-06,1-Sep-06,1-Sep-06,ARV,Adult,SUN PHARMACEUTICAL INDUSTRIES LTD (RANBAXY LAB...,...,60,31920,127360.8,3.99,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,NaN
4,16,Vietnam,Direct Drop,Air,11-Aug-06,11-Aug-06,11-Aug-06,ARV,Adult,Aurobindo Pharma Limited,...,60,38000,121600,3.2,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,NaN

#### Test functionality with Absolute Path for files

In [10]:
import src.data_loader as dl

In [11]:
project_root = Path("..").resolve()
sys.path.append(str(project_root))
project_root

WindowsPath('E:/jcuenca/OneDrive - GUSCanada/4toTerm/01_AgileSoftware/02_Assignment2/supply/Supply-Chain-Shipment-Summary-Tool')

In [12]:
print(dl.PROJECT_ROOT)
print(dl.CLEAN_DATA_PATH)
print(dl.CLEAN_DATA_PATH.exists())

E:\jcuenca\OneDrive - GUSCanada\4toTerm\01_AgileSoftware\02_Assignment2\supply\Supply-Chain-Shipment-Summary-Tool
E:\jcuenca\OneDrive - GUSCanada\4toTerm\01_AgileSoftware\02_Assignment2\supply\Supply-Chain-Shipment-Summary-Tool\data\supply_delivery_history_clean.csv
True

In [13]:
df_RowData2 = load_raw_data()
df_RowData2.head()

,ID,Country,Fulfill Via,Shipment Mode,Scheduled Delivery Date,Delivered to Client Date,Delivery Recorded Date,Product Group,Sub Classification,Vendor,...,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,Côte d'Ivoire,Direct Drop,Air,2-Jun-06,2-Jun-06,2-Jun-06,HRDT,HIV test,RANBAXY Fine Chemicals LTD.,...,30,19,551,29,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,NaN
1,3,Vietnam,Direct Drop,Air,14-Nov-06,14-Nov-06,14-Nov-06,ARV,Pediatric,Aurobindo Pharma Limited,...,240,1000,6200,6.2,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,NaN
2,4,Côte d'Ivoire,Direct Drop,Air,27-Aug-06,27-Aug-06,27-Aug-06,HRDT,HIV test,Abbott GmbH & Co. KG,...,100,500,40000,80,0.8,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,NaN
3,15,Vietnam,Direct Drop,Air,1-Sep-06,1-Sep-06,1-Sep-06,ARV,Adult,SUN PHARMACEUTICAL INDUSTRIES LTD (RANBAXY LAB...,...,60,31920,127360.8,3.99,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,NaN
4,16,Vietnam,Direct Drop,Air,11-Aug-06,11-Aug-06,11-Aug-06,ARV,Adult,Aurobindo Pharma Limited,...,60,38000,121600,3.2,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,NaN

In [7]:
df_CleanData2 = load_clean_data("../data/supply_delivery_history_clean.csv")
df_CleanData2.head()

,ID,Country,Fulfill Via,Shipment Mode,Scheduled Delivery Date,Delivered to Client Date,Delivery Recorded Date,Product Group,Sub Classification,Vendor,...,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,Côte d'Ivoire,Direct Drop,Air,2-Jun-06,2-Jun-06,2-Jun-06,HRDT,HIV test,RANBAXY Fine Chemicals LTD.,...,30,19,551,29,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,NaN
1,3,Vietnam,Direct Drop,Air,14-Nov-06,14-Nov-06,14-Nov-06,ARV,Pediatric,Aurobindo Pharma Limited,...,240,1000,6200,6.2,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,NaN
2,4,Côte d'Ivoire,Direct Drop,Air,27-Aug-06,27-Aug-06,27-Aug-06,HRDT,HIV test,Abbott GmbH & Co. KG,...,100,500,40000,80,0.8,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,NaN
3,15,Vietnam,Direct Drop,Air,1-Sep-06,1-Sep-06,1-Sep-06,ARV,Adult,SUN PHARMACEUTICAL INDUSTRIES LTD (RANBAXY LAB...,...,60,31920,127360.8,3.99,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,NaN
4,16,Vietnam,Direct Drop,Air,11-Aug-06,11-Aug-06,11-Aug-06,ARV,Adult,Aurobindo Pharma Limited,...,60,38000,121600,3.2,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,NaN